### ISSUE TITLE
Can an external to the GES Network sign up ?

### ISSUE THREAD

**Issue by RedHotMan** [Skumb/G-Esport#12]
**Is your feature request related to a problem? Please describe.**
Hum, I don't think so, it's more like a question, a suggestion.

**Question**
I saw that we have to be in `GES Network` to be able to use your application.
My question is if someone is external to the `GES Network`, can he sign up and use your application. It would be great to invite a friend of mine to join use for example. 

Thanks for your answer

**Comment by Skumb** [comment]
Hello, thanks for your contribution,

At the moment we're only approving GES Network accounts, this is why the project is named "G-Esport", but in the future, we might open approvation for external accounts, stay tuned.

Thanks
